### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by dmyersturnbull** [muuki88/sbt-slick#11]
Is it easy to cross-compile this for Scala 2.12?

**Comment by muuki88** [comment]
This is an sbt-plugin. So we would have to migrate it to sbt 1.0 for Scala 2.12.
Would you like to try that :)

**Comment by dmyersturnbull** [comment]
Isn't the most recent of sbt just 0.13.15? I'm happy to sumit a pull request, but I could use some guidance because I've never developed a plugin before.

**Comment by muuki88** [comment]
Yes. 0.13.15 is the current stable release, which is on Scala 2.10. the new 1.0-M1 is on Scala 2.12 IIRC

**Comment by muuki88** [comment]
I'll write in more detail during the weekend
