### ISSUE TITLE
Sbt 1.0.x support

### ISSUE THREAD

**Issue by pbassiner** [muuki88/sbt-slick#12]
Hi @muuki88, do you have any plans to add support for sbt 1.0.x? Since the migration requires upgrading to Scala 2.12.x I assume you'll need to cross publish `sbt-slick` for 2.10.x, 2.11.x and 2.12.x (if you want to keep backwards compatibility). I have no experience in dealing with cross version publishing but I'd gladly help if it's necessary.

Thanks!

**Comment by muuki88** [comment]
Hi @pbassiner

Thanks for your kind request. I'm not actively maintaining this project, but I would merge a pull request. Also I haven't used slick in ages. I wonder if slick doesn't provide an SBT plugin itself?

Still. If you have the time to make a PR, I'll give you some hints on how to cross build SBT. I'm currently on vaccination and will be back on the 22.10.

**Comment by pbassiner** [comment]
Hi @muuki88,
Slick doesn't provide an sbt plugin but they have [this example](https://github.com/slick/slick-codegen-example) using a custom task which, after adapting it to sbt `1.0.x`, works as expected.

Thanks anyway!

**Comment by muuki88** [comment]
Cool 😎 thanks for sharing and take care 😊
